### ISSUE TITLE
Error when saving Npc

### ISSUE THREAD

**Issue by CyberSpongie** [windy1/Peeps#1]
So all features work fine just i am having an error when it comes down to saving the npc 
here is the error log http://pastebin.com/cNkiqtq0
and i am using SpongeForge 1.10.2-2171-5.1.0-BETA-2006

EDIT: can you also add permission nodes so normal player cannot use this thanks
EDIT: can you also add another feature so if player right click the npc it can run commands  thanks

**Comment by windy1** [comment]
This plugin is definitely not meant for general use yet and is still very early in development. Permissions are definitely going to be added just haven't gotten around to it yet. That being said, this bug has been fixed in https://github.com/SpongePowered/SpongeAPI/commit/13fffcefb15865fec8e6b65660ec555d4d3b464e and will be in recent 6.0.0 builds.

**Comment by CyberSpongie** [comment]
Ohh sorry i tho this was for 1.10 my bad and sorry i knew this plugin was early development is that this kind of plugin is soooo much useful thanks for making it 👍
